### ISSUE TITLE
Modify the duration of the Popup Window?

### ISSUE THREAD

**Issue by sahsuvar** [Boteium/bashbullet#2]
Hi there,

ist it planned or possible to edit the duration of the popup Window for bashbullet?
I can't find a line in the config file.

Greets

**Comment by Boteium** [comment]
Currently, the only way is to use custom_command and mirror_command. e.g. "notify-send -t DURATION ...". So, you can only change these two kinds of pop-up notifications.

But it may or may not work because not all notification daemon support this. For example, it won't work with notify-osd if it's isn't running under a complete gnome desktop environment. 

BTW, If "notify-send -t " works for you, what kinds of pop-up notifications would you want to change ? It should be a simple thing to include in the next version.

**Comment by sahsuvar** [comment]
Hi Boteium,
sorry that I'm answering that late, but I had a busy week. "notify-send -t" was the right command I was looking for. 

I just want to mimic the popup duration like in windows 7sec~, so that all popups close after that.

Thanks for answering and keep codin!
